### PR TITLE
Gaurav van patch 1

### PR DESCRIPTION
**Pull request by Gaurav-Van**
#### Respected Team Leader,
This Pull request Contains Analysis of Comments and their Classifications.

- Contains Graphs

In my Opinion Next Step Should be to pre-process the text / comments using NLP but before that  a Team Discussion should happen 

I was free so I did the analysis

Kindly, Check this Pull request and if it fulfils the requirement then merging this would be a Step Forward in this Project

### CODE REVIEW

**Comment by keinisha** [comment]
bruh 💀

**Comment by Gaurav-Van** [comment]
:)

**Review by keinisha — APPROVED** [review]
Good work! Also great job being more productive than all of us x-x

**Comment by Gaurav-Van** [comment]
*Also great job being more productive than all of us x-x*
Wahhh but no
Just more Free / Vela not Productive

**Pull request merged**
